server:
  port: ":8080"
  host: "localhost"
  read_timeout: 30s
  write_timeout: 30s

database:
  host: "your-database-host"
  port: 5432
  user: "your-database-user"
  password: "your-database-password"
  dbname: "ChatApp"
  sslmode: "require"
  timezone: "UTC"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

jwt:
  secret: "CHANGE-THIS-TO-A-SECURE-SECRET-KEY-IN-PRODUCTION"
  expire_hours: 24
  issuer: "chatapp"

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  read_deadline: 60s
  write_deadline: 10s
  ping_period: 54s

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"

logging:
  level: "info"
  format: "json"
  output: "stdout"

app:
  name: "ChatApp"
  version: "1.0.0"
  debug: true
  environment: "development"

minio:
  endpoint: "127.0.0.1:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "chatapp"
  use_ssl: false
